package io.model;

import com.fasterxml.jackson.annotation.*;
import java.util.List;

@lombok.Data
public class ApplicationLiability {
    private Double annualInterestRate;
    private Double availableForRedrawAmount;
    private Double balloonRepaymentAmount;
    private String balloonRepaymentDate;
    private ClearingFromList clearingFromOtherSource;
    private Double clearingFromOtherSourceAmount;
    private ClearingFromList clearingFromThisLoan;
    private Double clearingFromThisLoanAmount;
    private YesNoList closingOnSettlement;
    private CreditCardTypeList creditCardType;
    private Double creditLimit;
    private String creditRiskGrade;
    private String description;
    private YesNoList hasArrears;
    private YesNoList hasPreviousArrears;
    private YesNoList hasUndrawnFunds;
    private Double inAdvanceAmount;
    private InterestChargeFrequencyList interestCalculationFrequency;
    private InterestChargeFrequencyList interestChargeFrequency;
    private YesNoList limitExceededCurrently;
    private YesNoList limitExceededPreviously;
    private String maturityDate;
    private Double minimumRepaymentRate;
    private NccpStatusList nccpStatus;
    private YesNoList negativelyGeared;
    private Double negativelyGearedPercentage;
    private Double newLimit;
    private Double nonCapitalisedInterest;
    private Double originalAmount;
    private PrimaryPurposeLoanPurposeList originalLoanPurpose;
    private String originationDate;
    private Double outstandingBalance;
    private YesNoList overdrawn;
    private String productCode;
    private String productName;
    private Double refinanceAmount;
    private Double refinanceCosts;
    private String repaidDate;
    private YesNoList secured;
    private YesNoList smsfLoan;
    private YesNoList suspended;
    private LiabilityTypeList type;
    private Double undrawnAmount;
    private String uniqueID;
    private YesNoList writtenOff;
    private FinancialAccountType accountNumber;
    private LiabilityArrears arrears;
    private List<ContinuingRepayment> continuingRepayment;
    private List<DiscountMarginElement> discountMargin;
    private DocumentationInstructionsType documentationInstructions;
    private LiabilityDSH dsh;
    private LiabilityFeaturesSelected featuresSelected;
    private List<LiabilityLendingPurpose> lendingPurpose;
    private OriginalTerm originalTerm;
    private PercentOwned percentOwned;
    private List<LiabilityRateComposition> rateComposition;
    private RemainingTerm remainingTerm;
    private List<LiabilityRepayment> repayment;
    private List<LiabilitySecurity> security;
    private LiabilitySoftware software;
    private List<LiabilityTermsAndCondition> termsAndConditions;
}
