package io.model;

import java.io.IOException;
import com.fasterxml.jackson.annotation.*;

public enum FinancialInstitutionList {
    AAMI, AAPBS_SETTLEMENTS_SERVICES, ABN_AMRO, ADELAIDE_BANK, ADVANTEDGE, AFG_HOME_LOANS, AGC, ALLIANZ, ALLSTATE_HOME_LOANS, AMERICAN_EXPRESS, AMG, AMIC, AMIST, AMP, AMS, ANZ_BANK, ANZ_WEALTH, AON_MASTER_TRUST, API, ARAB_BANK_OF_AUSTRALIA, ARMIDALE_BUILDING_SOCIETY, ASAHI_BANK, AUSSIE_HOME_LOANS, AUSSIE_MASTERCARD, AUSSIE_MORTGAGE_LTD, AUSTRALIAN_CATHOLIC, AUSTRALIAN_DEFENCE_CREDIT_UNION, AUSTRALIAN_EAGLE, AUSTRALIAN_ETHICAL, AUSTRALIAN_FIRST_MORTGAGE, AUSTRALIAN_PENSIONERS_INSURANCE, AUSTRALIAN_SUPER, AUSTRALIAN_UNITY_BUILDING_SOCIETY, AUSTRALIA_CENTRAL_CREDIT_UNION, AUST_ALLIANCE, AUST_SAFE, AUSWIDE_BANK, AVCO, AV_SUPER, AXA, BANKERS_TRUST_AUSTRALIA, BANKWEST, BANK_AUSTRALIA, BANK_OF_AMERICA, BANK_OF_CHINA, BANK_OF_MELBOURNE, BANK_OF_QUEENSLAND, BANK_OF_TOKYO_MITSUBISHI, BANK_SA, BANQUE_NATIONALE_DE_PARIS, BARCLAYS, BARNES_HOME_LOANS, BASS_AND_EQUITABLE_BUILDING_SOCIETY, BENDIGO_BANK, BETTER_CHOICE, BETTER_MORTGAGE_CORPORATION, BETTER_MORTGAGE_MGMT, BEYOND_BANK_AUSTRALIA, BLUEBAY_HOME_LOANS, BLUESTONE, BMW_AUSTRALIA, BOQ, BRIGHTEN_HOME_LOANS, BROKEN_HILL_COMMUNITY_CREDIT_UNION, BUILDING_SOCIETY_MP, BUSSQ, BUYERS_EDGE, CAPITAL_FINANCE, CAPRICORNIA_CREDIT_UNION, CARE_SUPER, CASH_DOCTORS, CATHOLIC_CHURCH, CATHOLIC_SUPER, CBA, CBFC, CBUS, CERTEGY, CGU, CHALLENGE_BANK, CHASE_MANHATTAN_BANK, CHEQUECASH_PTY_LTD, CHOICE_LEND, CHRISTIAN_SUPER, CHU, CIC, CIL, CIRCLE_CREDIT_UNION, CITIBANK, CITYWIDE_HOME_LOANS, CITY_COAST_CREDIT_UNION, CIT_CREDIT_PTY, CLUB_PLUS_SUPER, COASTLINE_CREDIT_UNION, COLONIAL, COLONIAL_FIRST_STATE, COLONIAL_MUTUAL, COMMERCIAL_UNION, COMMONWEALTH_BANK, COMM_BANK_FINANCIAL_PLANNER, COMM_INSURE, CONNECTIVE_HOME_LOANS, CO_OPERATIVE_INS_CO, CPS_CREDIT_UNION, CREDIT_CORP, CREDIT_UNION_AUSTRALIA, CREDIT_UNION_FINANCIAL_SERVICES, CREDIT_UNION_SA, CREDIT_UNION_SETTLEMENT_SERVICES, CUA, CUMIS, CUSCAL, CUSTOM_CREDIT, DAIMLERCHRYSLER_FINANCE, DAI_ICHI_KANGO_BANK, DEBT_PURCHASE_AUSTRALIA, DEFENCE_BANK, DEFENCE_CREDIT, DEFENCE_FORCE_CREDIT_UNION_LIMITED, DEFENCE_SERVICES_HOMES, DEUTSCHE_BANK, DINERS_CLUB, DNISTER_UKRAINIAN_CREDIT_CO_OPERATIVE, EECU, EISS, ELCOM_CREDIT_UNION, ELDERS, ENERGY_SUPER, EQUITY_SUPER, ESANDA, ESSENTIAL_SUPER, EZY_BANK, FAI, FAST_LEND, FEDERATION, FIRE_BRIGADES_CREDIT_UNION, FIRE_SERVICE_CREDIT_UNION, FIRSTMAC, FIRST_CHOICE_CREDIT_UNION, FIRST_NATIONAL_BANK_OF_CHICAGO, FIRST_PERMANENT_HOME_LOANS, FIRST_PROVINCIAL_BUILDING_SOCIETY, FIRST_STATE_SUPER, FIRST_SUPER, FLEXIRENT, FORD_CREDIT, FORTIS, FUNDCORP, FUTURE_FINANCIAL, GATEWAY_CREDIT_UNION, GENWORTH, GE_AUTOMOTIVE, GE_CAPITAL_FINANCE, GE_CAPITAL_FINANCE_GO_MASTERCARD, GE_CREDIT_LINE, GE_FINANCE, GE_MONEY_AUST_PTY_LTD, GE_MORTGAGES, GIO, GIO_BUILDING_SOCIETY, GMAC_FINANCE, GRACE_BROS, GRE, GREATER_BUILDING_SOCIETY, GREAT_PACIFIC_FINANCIAL, GUILD, HANOVER_CONSUMER_FINANCE, HBF, HERITAGE, HESTA, HOMELOANS_LTD, HOMESIDE, HOMESTART_FINANCE, HOMESWEST, HOME_BUILDING_SOCIETY, HSBC, HUME_BUILDING_SOCIETY, IBJ_AUSTRALIA_BANK, IDEN, IGNITE, ILLAWARRA_BUILDING_SOCIETY, IMB_LTD, INC_INVEST, ING, ING_MERCANTILE_MUTUAL_BANK, INTECH_CREDIT_UNION, INTERNATIONAL_ACCEPTANCE, INTERNATIONAL_COMMERCIAL_BANK_OF_CHINA, INVESTEC, IN_TRUST, IOOF_BUILDING_SOCIETY, KEYSTART_HOME_LOANS, KINETIC, KWIK_KASH_INTERNATIONAL, LA_TROBE, LEGAL_SUPER, LIBERTY, LION_FINANCE, LOANAVE, LOCAL_GOVERNMENT, LOMBARD_FINANCE, LUCRF, MACARTHUR_CREDIT_UNION, MACKAY_PERMANENT_BUILDING_SOCIETY, MACQUARIE, MAITLAND_MUTUAL_BUILDING_SOCIETY, MANUFACTURE_MUTUAL, MAP, MEDIA_SUPER, MEDIPLAN_AUSTRALIA, MEMBERS_EQUITY_BANK, MERCANTILE_MUTUAL, MERCER_WEALTH, ME_BANK, MIDLAND_BANK_PLC, MIIP, MINE_WEALTH_AND_WELLBEING, MIS, MITCHELL_BUILDING_SOCIETY, MKM_CAPITAL, MLC, MMI, MORGAN_GUARANTY_TRUST_BANK_OF_NEW_YORK, MORTGAGE_EZY, MORTGAGE_HOUSE, MORTGAGE_MART, MTAA, MUTUAL_COMMUNITY, M_CAPITOL, NAB, NATIONAL_MORTGAGE_CORPORATION, NATWEST_MARKETS_AUSTRALIA, NCUIS, NEWCASTLE_PERMANENT_BUILDING_SOCIETY, NGS, NORTHERN_BUILDING_SOCIETY, NRMA, NSF_SUPER, NSW_HOME_LOANS, NSW_TEACHERS_CREDIT_UNION, NZI, ONE_ANSWER, ORIX, OTHER, OVERSEAS_CHINESE_BANKING_CORPORATION, PARAMOUNT, PAYDAY_CENTRAL, PENSIONERS_INSURANCE, PEOPLE_S_CHOICE_CREDIT_UNION, PEPPER, PERPETUAL_LIMITED, PERPETUAL_TRUSTEE, PIONEER_PERMANENT_BUILDING_SOCIETY, PLAN_LEND, PLUM, POLICE_AND_NURSES, POLICE_CREDIT_UNION, POLICE_CREDIT_UNION_NSW, POWERSTATE_CREDIT_UNION, PRIMARY_INDUSTRY_BANK_OF_AUSTRALIA, PRIME, PROSPECT_CREDIT_UNION, PUBLIC_TRUSTEE, PULSE_CREDIT_UNION, QANTAS_CREDIT_UNION, QBE, QUDOS_BANK, QUEENSLAND_COUNTRY_CREDIT_UNION, QUEENSLAND_CREDIT_UNION, QUEENSLAND_INDUSTRY_DEVELOPMENT_CORP, QUEENSLAND_PROFESSIONAL_CREDIT_UNION, QUEENSLAND_TEACHERS_CREDIT_UNION, RAC, RACV, RAC_WA, RADIO_RENTALS, RAILWAYS_CREDIT_UNION, RAMS, REA_HOME_LOANS, REPCOL, RESERVE_BANK_OF_AUSTRALIA, RESI, RESIMAC, RESI_MORTGAGE_CORPORATION, ROYAL_LIFE, RUSSELL_INVESTMENTS, SAFROCK_FINANCE, SANWA_AUSTRALIA_FINANCE_LIMITED, SAVINGS_AND_LOANS_CREDIT_UNION, SGIC, SGIO, SHANNONS, SMART_SAVE, SOUTHERN_CROSS_CREDIT_UNION, SOVEREIGN_CREDIT, STANDARD_CHARTERED_BANK_AUST, STATEWIDE, STATE_STREET_BANK_AND_TRUST_COMPANY, STRONGHOLD, ST_ANDREW, ST_GEORGE, SUMMERLAND_CREDIT_UNION, SUNCORP, SUNCORP_METWAY, SUNSUPER, SUN_ALLIANCE, SWANN, TAS_PLAN, TEACHERS_CREDIT_UNION, TEACHERS_MUTUAL, TERRITORY_MUTUAL_BUILDING_SOCIETY, THE_ROCK, TONTO_HOME_LOANS, TOWN_AND_COUNTRY_BANK, TOYOTA_FINANCE_AUSTRALIA, TRUST_BANK_OF_TASMANIA, TWUSUPER, UNITED_CREDIT_UNION, UNITED_OVERSEAS_BANK, UNIVERSITY_CREDIT_SOCIETY, U_BANK, VACC, VERO, VICTORIA_TEACHERS_CREDIT_UNION_LTD, VIC_SUPER, VIRGIN_SUPER, VISIONS, WESTERN_QBE, WESTFARMERS, WESTPACK_INSURANCE_SERVICES, WESTPAC_BANK, WIDE_BAY_CAPRICORN_BUILDING_SOCIETY, WIZARD, WORLD_MARINE_AND_GENERAL, ZURICH;

    @JsonValue
    public String toValue() {
        switch (this) {
            case AAMI: return "AAMI";
            case AAPBS_SETTLEMENTS_SERVICES: return "AAPBS Settlements Services";
            case ABN_AMRO: return "ABN AMRO";
            case ADELAIDE_BANK: return "Adelaide Bank";
            case ADVANTEDGE: return "Advantedge";
            case AFG_HOME_LOANS: return "AFG Home Loans";
            case AGC: return "AGC";
            case ALLIANZ: return "Allianz";
            case ALLSTATE_HOME_LOANS: return "Allstate Home Loans";
            case AMERICAN_EXPRESS: return "American Express";
            case AMG: return "AMG";
            case AMIC: return "AMIC";
            case AMIST: return "AMIST";
            case AMP: return "AMP";
            case AMS: return "AMS";
            case ANZ_BANK: return "ANZ Bank";
            case ANZ_WEALTH: return "ANZ Wealth";
            case AON_MASTER_TRUST: return "Aon Master Trust";
            case API: return "API";
            case ARAB_BANK_OF_AUSTRALIA: return "Arab Bank of Australia";
            case ARMIDALE_BUILDING_SOCIETY: return "Armidale Building Society";
            case ASAHI_BANK: return "Asahi Bank";
            case AUSSIE_HOME_LOANS: return "Aussie Home Loans";
            case AUSSIE_MASTERCARD: return "Aussie Mastercard";
            case AUSSIE_MORTGAGE_LTD: return "Aussie Mortgage Ltd";
            case AUSTRALIAN_CATHOLIC: return "Australian Catholic";
            case AUSTRALIAN_DEFENCE_CREDIT_UNION: return "Australian Defence Credit Union";
            case AUSTRALIAN_EAGLE: return "Australian Eagle";
            case AUSTRALIAN_ETHICAL: return "Australian Ethical";
            case AUSTRALIAN_FIRST_MORTGAGE: return "Australian First Mortgage";
            case AUSTRALIAN_PENSIONERS_INSURANCE: return "Australian Pensioners Insurance";
            case AUSTRALIAN_SUPER: return "AustralianSuper";
            case AUSTRALIAN_UNITY_BUILDING_SOCIETY: return "Australian Unity Building Society";
            case AUSTRALIA_CENTRAL_CREDIT_UNION: return "Australia Central Credit Union";
            case AUST_ALLIANCE: return "Aust Alliance";
            case AUST_SAFE: return "AustSafe";
            case AUSWIDE_BANK: return "Auswide Bank";
            case AVCO: return "AVCO";
            case AV_SUPER: return "AV Super";
            case AXA: return "AXA";
            case BANKERS_TRUST_AUSTRALIA: return "Bankers Trust Australia";
            case BANKWEST: return "Bankwest";
            case BANK_AUSTRALIA: return "Bank Australia";
            case BANK_OF_AMERICA: return "Bank of America";
            case BANK_OF_CHINA: return "Bank of China";
            case BANK_OF_MELBOURNE: return "Bank of Melbourne";
            case BANK_OF_QUEENSLAND: return "Bank of Queensland";
            case BANK_OF_TOKYO_MITSUBISHI: return "Bank of Tokyo-Mitsubishi";
            case BANK_SA: return "Bank SA";
            case BANQUE_NATIONALE_DE_PARIS: return "Banque Nationale De Paris";
            case BARCLAYS: return "Barclays";
            case BARNES_HOME_LOANS: return "Barnes Home Loans";
            case BASS_AND_EQUITABLE_BUILDING_SOCIETY: return "Bass and Equitable Building Society";
            case BENDIGO_BANK: return "Bendigo Bank";
            case BETTER_CHOICE: return "Better Choice";
            case BETTER_MORTGAGE_CORPORATION: return "Better Mortgage Corporation";
            case BETTER_MORTGAGE_MGMT: return "Better Mortgage Mgmt";
            case BEYOND_BANK_AUSTRALIA: return "Beyond Bank Australia";
            case BLUEBAY_HOME_LOANS: return "Bluebay Home Loans";
            case BLUESTONE: return "Bluestone";
            case BMW_AUSTRALIA: return "BMW Australia";
            case BOQ: return "BOQ";
            case BRIGHTEN_HOME_LOANS: return "Brighten Home Loans";
            case BROKEN_HILL_COMMUNITY_CREDIT_UNION: return "Broken Hill Community Credit Union";
            case BUILDING_SOCIETY_MP: return "Building Society MP";
            case BUSSQ: return "BUSSQ";
            case BUYERS_EDGE: return "Buyers Edge";
            case CAPITAL_FINANCE: return "Capital Finance";
            case CAPRICORNIA_CREDIT_UNION: return "Capricornia Credit Union";
            case CARE_SUPER: return "CareSuper";
            case CASH_DOCTORS: return "Cash Doctors";
            case CATHOLIC_CHURCH: return "Catholic Church";
            case CATHOLIC_SUPER: return "Catholic Super";
            case CBA: return "CBA";
            case CBFC: return "CBFC";
            case CBUS: return "CBUS";
            case CERTEGY: return "Certegy";
            case CGU: return "CGU";
            case CHALLENGE_BANK: return "Challenge Bank";
            case CHASE_MANHATTAN_BANK: return "Chase Manhattan Bank";
            case CHEQUECASH_PTY_LTD: return "Chequecash Pty Ltd";
            case CHOICE_LEND: return "ChoiceLend";
            case CHRISTIAN_SUPER: return "Christian Super";
            case CHU: return "CHU";
            case CIC: return "CIC";
            case CIL: return "CIL";
            case CIRCLE_CREDIT_UNION: return "Circle Credit Union";
            case CITIBANK: return "Citibank";
            case CITYWIDE_HOME_LOANS: return "Citywide Home Loans";
            case CITY_COAST_CREDIT_UNION: return "City Coast Credit Union";
            case CIT_CREDIT_PTY: return "CIT Credit Pty";
            case CLUB_PLUS_SUPER: return "Club Plus Super";
            case COASTLINE_CREDIT_UNION: return "Coastline Credit Union";
            case COLONIAL: return "Colonial";
            case COLONIAL_FIRST_STATE: return "Colonial First State";
            case COLONIAL_MUTUAL: return "Colonial Mutual";
            case COMMERCIAL_UNION: return "Commercial Union";
            case COMMONWEALTH_BANK: return "Commonwealth Bank";
            case COMM_BANK_FINANCIAL_PLANNER: return "CommBank Financial Planner";
            case COMM_INSURE: return "CommInsure";
            case CONNECTIVE_HOME_LOANS: return "Connective Home Loans";
            case CO_OPERATIVE_INS_CO: return "Co Operative Ins Co";
            case CPS_CREDIT_UNION: return "CPS Credit Union";
            case CREDIT_CORP: return "Credit Corp";
            case CREDIT_UNION_AUSTRALIA: return "Credit Union Australia";
            case CREDIT_UNION_FINANCIAL_SERVICES: return "Credit Union Financial Services";
            case CREDIT_UNION_SA: return "Credit Union SA";
            case CREDIT_UNION_SETTLEMENT_SERVICES: return "Credit Union Settlement Services";
            case CUA: return "CUA";
            case CUMIS: return "Cumis";
            case CUSCAL: return "Cuscal";
            case CUSTOM_CREDIT: return "Custom Credit";
            case DAIMLERCHRYSLER_FINANCE: return "Daimlerchrysler Finance";
            case DAI_ICHI_KANGO_BANK: return "Dai-Ichi Kango Bank";
            case DEBT_PURCHASE_AUSTRALIA: return "Debt Purchase Australia";
            case DEFENCE_BANK: return "Defence Bank";
            case DEFENCE_CREDIT: return "Defence Credit";
            case DEFENCE_FORCE_CREDIT_UNION_LIMITED: return "Defence Force Credit Union Limited";
            case DEFENCE_SERVICES_HOMES: return "Defence Services Homes";
            case DEUTSCHE_BANK: return "Deutsche Bank";
            case DINERS_CLUB: return "Diners Club";
            case DNISTER_UKRAINIAN_CREDIT_CO_OPERATIVE: return "Dnister Ukrainian Credit Co-operative";
            case EECU: return "EECU";
            case EISS: return "EISS";
            case ELCOM_CREDIT_UNION: return "ELCOM Credit Union";
            case ELDERS: return "Elders";
            case ENERGY_SUPER: return "Energy Super";
            case EQUITY_SUPER: return "Equity Super";
            case ESANDA: return "Esanda";
            case ESSENTIAL_SUPER: return "Essential Super";
            case EZY_BANK: return "Ezy Bank";
            case FAI: return "FAI";
            case FAST_LEND: return "FASTLend";
            case FEDERATION: return "Federation";
            case FIRE_BRIGADES_CREDIT_UNION: return "Fire Brigades Credit Union";
            case FIRE_SERVICE_CREDIT_UNION: return "Fire Service Credit Union";
            case FIRSTMAC: return "Firstmac";
            case FIRST_CHOICE_CREDIT_UNION: return "First Choice Credit Union";
            case FIRST_NATIONAL_BANK_OF_CHICAGO: return "First National Bank of Chicago";
            case FIRST_PERMANENT_HOME_LOANS: return "First Permanent Home Loans";
            case FIRST_PROVINCIAL_BUILDING_SOCIETY: return "First Provincial Building Society";
            case FIRST_STATE_SUPER: return "First State Super";
            case FIRST_SUPER: return "First Super";
            case FLEXIRENT: return "Flexirent";
            case FORD_CREDIT: return "Ford Credit";
            case FORTIS: return "Fortis";
            case FUNDCORP: return "Fundcorp";
            case FUTURE_FINANCIAL: return "Future Financial";
            case GATEWAY_CREDIT_UNION: return "Gateway Credit Union";
            case GENWORTH: return "Genworth";
            case GE_AUTOMOTIVE: return "GE Automotive";
            case GE_CAPITAL_FINANCE: return "GE Capital Finance";
            case GE_CAPITAL_FINANCE_GO_MASTERCARD: return "GE Capital Finance (Go Mastercard)";
            case GE_CREDIT_LINE: return "GE Credit Line";
            case GE_FINANCE: return "Ge Finance";
            case GE_MONEY_AUST_PTY_LTD: return "GE Money Aust Pty Ltd";
            case GE_MORTGAGES: return "GE Mortgages";
            case GIO: return "GIO";
            case GIO_BUILDING_SOCIETY: return "GIO Building Society";
            case GMAC_FINANCE: return "GMAC Finance";
            case GRACE_BROS: return "Grace Bros";
            case GRE: return "GRE";
            case GREATER_BUILDING_SOCIETY: return "Greater Building Society";
            case GREAT_PACIFIC_FINANCIAL: return "Great Pacific Financial";
            case GUILD: return "Guild";
            case HANOVER_CONSUMER_FINANCE: return "Hanover Consumer Finance";
            case HBF: return "HBF";
            case HERITAGE: return "Heritage";
            case HESTA: return "HESTA";
            case HOMELOANS_LTD: return "Homeloans Ltd";
            case HOMESIDE: return "Homeside";
            case HOMESTART_FINANCE: return "Homestart Finance";
            case HOMESWEST: return "Homeswest";
            case HOME_BUILDING_SOCIETY: return "Home Building Society";
            case HSBC: return "HSBC";
            case HUME_BUILDING_SOCIETY: return "Hume Building Society";
            case IBJ_AUSTRALIA_BANK: return "IBJ Australia Bank";
            case IDEN: return "Iden";
            case IGNITE: return "Ignite";
            case ILLAWARRA_BUILDING_SOCIETY: return "Illawarra Building Society";
            case IMB_LTD: return "IMB Ltd";
            case INC_INVEST: return "INC Invest";
            case ING: return "ING";
            case ING_MERCANTILE_MUTUAL_BANK: return "ING Mercantile Mutual Bank";
            case INTECH_CREDIT_UNION: return "Intech Credit Union";
            case INTERNATIONAL_ACCEPTANCE: return "International Acceptance";
            case INTERNATIONAL_COMMERCIAL_BANK_OF_CHINA: return "International Commercial Bank of China";
            case INVESTEC: return "Investec";
            case IN_TRUST: return "InTrust";
            case IOOF_BUILDING_SOCIETY: return "IOOF Building Society";
            case KEYSTART_HOME_LOANS: return "Keystart Home Loans";
            case KINETIC: return "Kinetic";
            case KWIK_KASH_INTERNATIONAL: return "Kwik Kash International";
            case LA_TROBE: return "LaTrobe";
            case LEGAL_SUPER: return "Legal Super";
            case LIBERTY: return "Liberty";
            case LION_FINANCE: return "Lion Finance";
            case LOANAVE: return "Loanave";
            case LOCAL_GOVERNMENT: return "Local Government";
            case LOMBARD_FINANCE: return "Lombard Finance";
            case LUCRF: return "LUCRF";
            case MACARTHUR_CREDIT_UNION: return "Macarthur Credit Union";
            case MACKAY_PERMANENT_BUILDING_SOCIETY: return "Mackay Permanent Building Society";
            case MACQUARIE: return "Macquarie";
            case MAITLAND_MUTUAL_BUILDING_SOCIETY: return "Maitland Mutual Building Society";
            case MANUFACTURE_MUTUAL: return "Manufacture Mutual";
            case MAP: return "MAP";
            case MEDIA_SUPER: return "Media Super";
            case MEDIPLAN_AUSTRALIA: return "Mediplan Australia";
            case MEMBERS_EQUITY_BANK: return "Members Equity Bank";
            case MERCANTILE_MUTUAL: return "Mercantile Mutual";
            case MERCER_WEALTH: return "Mercer Wealth";
            case ME_BANK: return "ME Bank";
            case MIDLAND_BANK_PLC: return "Midland Bank PLC";
            case MIIP: return "MIIP";
            case MINE_WEALTH_AND_WELLBEING: return "Mine Wealth and Wellbeing";
            case MIS: return "MIS";
            case MITCHELL_BUILDING_SOCIETY: return "Mitchell Building Society";
            case MKM_CAPITAL: return "MKM Capital";
            case MLC: return "MLC";
            case MMI: return "MMI";
            case MORGAN_GUARANTY_TRUST_BANK_OF_NEW_YORK: return "Morgan Guaranty Trust Bank of New York";
            case MORTGAGE_EZY: return "Mortgage Ezy";
            case MORTGAGE_HOUSE: return "Mortgage House";
            case MORTGAGE_MART: return "Mortgage Mart";
            case MTAA: return "MTAA";
            case MUTUAL_COMMUNITY: return "Mutual Community";
            case M_CAPITOL: return "M Capitol";
            case NAB: return "NAB";
            case NATIONAL_MORTGAGE_CORPORATION: return "National Mortgage Corporation";
            case NATWEST_MARKETS_AUSTRALIA: return "Natwest Markets Australia";
            case NCUIS: return "NCUIS";
            case NEWCASTLE_PERMANENT_BUILDING_SOCIETY: return "Newcastle Permanent Building Society";
            case NGS: return "NGS";
            case NORTHERN_BUILDING_SOCIETY: return "Northern Building Society";
            case NRMA: return "NRMA";
            case NSF_SUPER: return "NSF Super";
            case NSW_HOME_LOANS: return "NSW Home Loans";
            case NSW_TEACHERS_CREDIT_UNION: return "NSW Teachers Credit Union";
            case NZI: return "NZI";
            case ONE_ANSWER: return "OneAnswer";
            case ORIX: return "ORIX";
            case OTHER: return "Other";
            case OVERSEAS_CHINESE_BANKING_CORPORATION: return "Overseas-Chinese Banking Corporation";
            case PARAMOUNT: return "Paramount";
            case PAYDAY_CENTRAL: return "Payday Central";
            case PENSIONERS_INSURANCE: return "Pensioners Insurance";
            case PEOPLE_S_CHOICE_CREDIT_UNION: return "People's Choice Credit Union";
            case PEPPER: return "Pepper";
            case PERPETUAL_LIMITED: return "Perpetual Limited";
            case PERPETUAL_TRUSTEE: return "Perpetual Trustee";
            case PIONEER_PERMANENT_BUILDING_SOCIETY: return "Pioneer Permanent Building Society";
            case PLAN_LEND: return "PLANLend";
            case PLUM: return "Plum";
            case POLICE_AND_NURSES: return "Police and Nurses";
            case POLICE_CREDIT_UNION: return "Police Credit Union";
            case POLICE_CREDIT_UNION_NSW: return "Police Credit Union (NSW)";
            case POWERSTATE_CREDIT_UNION: return "Powerstate Credit Union";
            case PRIMARY_INDUSTRY_BANK_OF_AUSTRALIA: return "Primary Industry Bank of Australia";
            case PRIME: return "Prime";
            case PROSPECT_CREDIT_UNION: return "Prospect Credit Union";
            case PUBLIC_TRUSTEE: return "Public Trustee";
            case PULSE_CREDIT_UNION: return "Pulse Credit Union";
            case QANTAS_CREDIT_UNION: return "QANTAS Credit Union";
            case QBE: return "QBE";
            case QUDOS_BANK: return "Qudos Bank";
            case QUEENSLAND_COUNTRY_CREDIT_UNION: return "Queensland Country Credit Union";
            case QUEENSLAND_CREDIT_UNION: return "Queensland Credit Union";
            case QUEENSLAND_INDUSTRY_DEVELOPMENT_CORP: return "Queensland Industry Development Corp";
            case QUEENSLAND_PROFESSIONAL_CREDIT_UNION: return "Queensland Professional Credit Union";
            case QUEENSLAND_TEACHERS_CREDIT_UNION: return "Queensland Teachers Credit Union";
            case RAC: return "RAC";
            case RACV: return "RACV";
            case RAC_WA: return "RAC WA";
            case RADIO_RENTALS: return "Radio Rentals";
            case RAILWAYS_CREDIT_UNION: return "Railways Credit Union";
            case RAMS: return "RAMS";
            case REA_HOME_LOANS: return "REA Home Loans";
            case REPCOL: return "Repcol";
            case RESERVE_BANK_OF_AUSTRALIA: return "Reserve Bank of Australia";
            case RESI: return "Resi";
            case RESIMAC: return "RESIMAC";
            case RESI_MORTGAGE_CORPORATION: return "RESI Mortgage Corporation";
            case ROYAL_LIFE: return "Royal Life";
            case RUSSELL_INVESTMENTS: return "Russell Investments";
            case SAFROCK_FINANCE: return "Safrock Finance";
            case SANWA_AUSTRALIA_FINANCE_LIMITED: return "Sanwa Australia Finance Limited";
            case SAVINGS_AND_LOANS_CREDIT_UNION: return "Savings And Loans Credit Union";
            case SGIC: return "SGIC";
            case SGIO: return "SGIO";
            case SHANNONS: return "Shannons";
            case SMART_SAVE: return "SmartSave";
            case SOUTHERN_CROSS_CREDIT_UNION: return "Southern Cross Credit Union";
            case SOVEREIGN_CREDIT: return "Sovereign Credit";
            case STANDARD_CHARTERED_BANK_AUST: return "Standard Chartered Bank Aust";
            case STATEWIDE: return "Statewide";
            case STATE_STREET_BANK_AND_TRUST_COMPANY: return "State Street Bank And Trust Company";
            case STRONGHOLD: return "Stronghold";
            case ST_ANDREW: return "St Andrew";
            case ST_GEORGE: return "St George";
            case SUMMERLAND_CREDIT_UNION: return "Summerland Credit Union";
            case SUNCORP: return "Suncorp";
            case SUNCORP_METWAY: return "Suncorp Metway";
            case SUNSUPER: return "Sunsuper";
            case SUN_ALLIANCE: return "Sun Alliance";
            case SWANN: return "Swann";
            case TAS_PLAN: return "TasPlan";
            case TEACHERS_CREDIT_UNION: return "Teachers Credit Union";
            case TEACHERS_MUTUAL: return "Teachers Mutual";
            case TERRITORY_MUTUAL_BUILDING_SOCIETY: return "Territory Mutual Building Society";
            case THE_ROCK: return "The Rock";
            case TONTO_HOME_LOANS: return "Tonto Home Loans";
            case TOWN_AND_COUNTRY_BANK: return "Town And Country Bank";
            case TOYOTA_FINANCE_AUSTRALIA: return "Toyota Finance Australia";
            case TRUST_BANK_OF_TASMANIA: return "Trust Bank of Tasmania";
            case TWUSUPER: return "TWUSUPER";
            case UNITED_CREDIT_UNION: return "United Credit Union";
            case UNITED_OVERSEAS_BANK: return "United Overseas Bank";
            case UNIVERSITY_CREDIT_SOCIETY: return "University Credit Society";
            case U_BANK: return "UBank";
            case VACC: return "VACC";
            case VERO: return "Vero";
            case VICTORIA_TEACHERS_CREDIT_UNION_LTD: return "Victoria Teachers Credit Union Ltd";
            case VIC_SUPER: return "VicSuper";
            case VIRGIN_SUPER: return "Virgin Super";
            case VISIONS: return "Visions";
            case WESTERN_QBE: return "Western QBE";
            case WESTFARMERS: return "Westfarmers";
            case WESTPACK_INSURANCE_SERVICES: return "Westpack Insurance Services";
            case WESTPAC_BANK: return "Westpac Bank";
            case WIDE_BAY_CAPRICORN_BUILDING_SOCIETY: return "Wide Bay Capricorn Building Society";
            case WIZARD: return "Wizard";
            case WORLD_MARINE_AND_GENERAL: return "World Marine and General";
            case ZURICH: return "Zurich";
        }
        return null;
    }

    @JsonCreator
    public static FinancialInstitutionList forValue(String value) throws IOException {
        if (value.equals("AAMI")) return AAMI;
        if (value.equals("AAPBS Settlements Services")) return AAPBS_SETTLEMENTS_SERVICES;
        if (value.equals("ABN AMRO")) return ABN_AMRO;
        if (value.equals("Adelaide Bank")) return ADELAIDE_BANK;
        if (value.equals("Advantedge")) return ADVANTEDGE;
        if (value.equals("AFG Home Loans")) return AFG_HOME_LOANS;
        if (value.equals("AGC")) return AGC;
        if (value.equals("Allianz")) return ALLIANZ;
        if (value.equals("Allstate Home Loans")) return ALLSTATE_HOME_LOANS;
        if (value.equals("American Express")) return AMERICAN_EXPRESS;
        if (value.equals("AMG")) return AMG;
        if (value.equals("AMIC")) return AMIC;
        if (value.equals("AMIST")) return AMIST;
        if (value.equals("AMP")) return AMP;
        if (value.equals("AMS")) return AMS;
        if (value.equals("ANZ Bank")) return ANZ_BANK;
        if (value.equals("ANZ Wealth")) return ANZ_WEALTH;
        if (value.equals("Aon Master Trust")) return AON_MASTER_TRUST;
        if (value.equals("API")) return API;
        if (value.equals("Arab Bank of Australia")) return ARAB_BANK_OF_AUSTRALIA;
        if (value.equals("Armidale Building Society")) return ARMIDALE_BUILDING_SOCIETY;
        if (value.equals("Asahi Bank")) return ASAHI_BANK;
        if (value.equals("Aussie Home Loans")) return AUSSIE_HOME_LOANS;
        if (value.equals("Aussie Mastercard")) return AUSSIE_MASTERCARD;
        if (value.equals("Aussie Mortgage Ltd")) return AUSSIE_MORTGAGE_LTD;
        if (value.equals("Australian Catholic")) return AUSTRALIAN_CATHOLIC;
        if (value.equals("Australian Defence Credit Union")) return AUSTRALIAN_DEFENCE_CREDIT_UNION;
        if (value.equals("Australian Eagle")) return AUSTRALIAN_EAGLE;
        if (value.equals("Australian Ethical")) return AUSTRALIAN_ETHICAL;
        if (value.equals("Australian First Mortgage")) return AUSTRALIAN_FIRST_MORTGAGE;
        if (value.equals("Australian Pensioners Insurance")) return AUSTRALIAN_PENSIONERS_INSURANCE;
        if (value.equals("AustralianSuper")) return AUSTRALIAN_SUPER;
        if (value.equals("Australian Unity Building Society")) return AUSTRALIAN_UNITY_BUILDING_SOCIETY;
        if (value.equals("Australia Central Credit Union")) return AUSTRALIA_CENTRAL_CREDIT_UNION;
        if (value.equals("Aust Alliance")) return AUST_ALLIANCE;
        if (value.equals("AustSafe")) return AUST_SAFE;
        if (value.equals("Auswide Bank")) return AUSWIDE_BANK;
        if (value.equals("AVCO")) return AVCO;
        if (value.equals("AV Super")) return AV_SUPER;
        if (value.equals("AXA")) return AXA;
        if (value.equals("Bankers Trust Australia")) return BANKERS_TRUST_AUSTRALIA;
        if (value.equals("Bankwest")) return BANKWEST;
        if (value.equals("Bank Australia")) return BANK_AUSTRALIA;
        if (value.equals("Bank of America")) return BANK_OF_AMERICA;
        if (value.equals("Bank of China")) return BANK_OF_CHINA;
        if (value.equals("Bank of Melbourne")) return BANK_OF_MELBOURNE;
        if (value.equals("Bank of Queensland")) return BANK_OF_QUEENSLAND;
        if (value.equals("Bank of Tokyo-Mitsubishi")) return BANK_OF_TOKYO_MITSUBISHI;
        if (value.equals("Bank SA")) return BANK_SA;
        if (value.equals("Banque Nationale De Paris")) return BANQUE_NATIONALE_DE_PARIS;
        if (value.equals("Barclays")) return BARCLAYS;
        if (value.equals("Barnes Home Loans")) return BARNES_HOME_LOANS;
        if (value.equals("Bass and Equitable Building Society")) return BASS_AND_EQUITABLE_BUILDING_SOCIETY;
        if (value.equals("Bendigo Bank")) return BENDIGO_BANK;
        if (value.equals("Better Choice")) return BETTER_CHOICE;
        if (value.equals("Better Mortgage Corporation")) return BETTER_MORTGAGE_CORPORATION;
        if (value.equals("Better Mortgage Mgmt")) return BETTER_MORTGAGE_MGMT;
        if (value.equals("Beyond Bank Australia")) return BEYOND_BANK_AUSTRALIA;
        if (value.equals("Bluebay Home Loans")) return BLUEBAY_HOME_LOANS;
        if (value.equals("Bluestone")) return BLUESTONE;
        if (value.equals("BMW Australia")) return BMW_AUSTRALIA;
        if (value.equals("BOQ")) return BOQ;
        if (value.equals("Brighten Home Loans")) return BRIGHTEN_HOME_LOANS;
        if (value.equals("Broken Hill Community Credit Union")) return BROKEN_HILL_COMMUNITY_CREDIT_UNION;
        if (value.equals("Building Society MP")) return BUILDING_SOCIETY_MP;
        if (value.equals("BUSSQ")) return BUSSQ;
        if (value.equals("Buyers Edge")) return BUYERS_EDGE;
        if (value.equals("Capital Finance")) return CAPITAL_FINANCE;
        if (value.equals("Capricornia Credit Union")) return CAPRICORNIA_CREDIT_UNION;
        if (value.equals("CareSuper")) return CARE_SUPER;
        if (value.equals("Cash Doctors")) return CASH_DOCTORS;
        if (value.equals("Catholic Church")) return CATHOLIC_CHURCH;
        if (value.equals("Catholic Super")) return CATHOLIC_SUPER;
        if (value.equals("CBA")) return CBA;
        if (value.equals("CBFC")) return CBFC;
        if (value.equals("CBUS")) return CBUS;
        if (value.equals("Certegy")) return CERTEGY;
        if (value.equals("CGU")) return CGU;
        if (value.equals("Challenge Bank")) return CHALLENGE_BANK;
        if (value.equals("Chase Manhattan Bank")) return CHASE_MANHATTAN_BANK;
        if (value.equals("Chequecash Pty Ltd")) return CHEQUECASH_PTY_LTD;
        if (value.equals("ChoiceLend")) return CHOICE_LEND;
        if (value.equals("Christian Super")) return CHRISTIAN_SUPER;
        if (value.equals("CHU")) return CHU;
        if (value.equals("CIC")) return CIC;
        if (value.equals("CIL")) return CIL;
        if (value.equals("Circle Credit Union")) return CIRCLE_CREDIT_UNION;
        if (value.equals("Citibank")) return CITIBANK;
        if (value.equals("Citywide Home Loans")) return CITYWIDE_HOME_LOANS;
        if (value.equals("City Coast Credit Union")) return CITY_COAST_CREDIT_UNION;
        if (value.equals("CIT Credit Pty")) return CIT_CREDIT_PTY;
        if (value.equals("Club Plus Super")) return CLUB_PLUS_SUPER;
        if (value.equals("Coastline Credit Union")) return COASTLINE_CREDIT_UNION;
        if (value.equals("Colonial")) return COLONIAL;
        if (value.equals("Colonial First State")) return COLONIAL_FIRST_STATE;
        if (value.equals("Colonial Mutual")) return COLONIAL_MUTUAL;
        if (value.equals("Commercial Union")) return COMMERCIAL_UNION;
        if (value.equals("Commonwealth Bank")) return COMMONWEALTH_BANK;
        if (value.equals("CommBank Financial Planner")) return COMM_BANK_FINANCIAL_PLANNER;
        if (value.equals("CommInsure")) return COMM_INSURE;
        if (value.equals("Connective Home Loans")) return CONNECTIVE_HOME_LOANS;
        if (value.equals("Co Operative Ins Co")) return CO_OPERATIVE_INS_CO;
        if (value.equals("CPS Credit Union")) return CPS_CREDIT_UNION;
        if (value.equals("Credit Corp")) return CREDIT_CORP;
        if (value.equals("Credit Union Australia")) return CREDIT_UNION_AUSTRALIA;
        if (value.equals("Credit Union Financial Services")) return CREDIT_UNION_FINANCIAL_SERVICES;
        if (value.equals("Credit Union SA")) return CREDIT_UNION_SA;
        if (value.equals("Credit Union Settlement Services")) return CREDIT_UNION_SETTLEMENT_SERVICES;
        if (value.equals("CUA")) return CUA;
        if (value.equals("Cumis")) return CUMIS;
        if (value.equals("Cuscal")) return CUSCAL;
        if (value.equals("Custom Credit")) return CUSTOM_CREDIT;
        if (value.equals("Daimlerchrysler Finance")) return DAIMLERCHRYSLER_FINANCE;
        if (value.equals("Dai-Ichi Kango Bank")) return DAI_ICHI_KANGO_BANK;
        if (value.equals("Debt Purchase Australia")) return DEBT_PURCHASE_AUSTRALIA;
        if (value.equals("Defence Bank")) return DEFENCE_BANK;
        if (value.equals("Defence Credit")) return DEFENCE_CREDIT;
        if (value.equals("Defence Force Credit Union Limited")) return DEFENCE_FORCE_CREDIT_UNION_LIMITED;
        if (value.equals("Defence Services Homes")) return DEFENCE_SERVICES_HOMES;
        if (value.equals("Deutsche Bank")) return DEUTSCHE_BANK;
        if (value.equals("Diners Club")) return DINERS_CLUB;
        if (value.equals("Dnister Ukrainian Credit Co-operative")) return DNISTER_UKRAINIAN_CREDIT_CO_OPERATIVE;
        if (value.equals("EECU")) return EECU;
        if (value.equals("EISS")) return EISS;
        if (value.equals("ELCOM Credit Union")) return ELCOM_CREDIT_UNION;
        if (value.equals("Elders")) return ELDERS;
        if (value.equals("Energy Super")) return ENERGY_SUPER;
        if (value.equals("Equity Super")) return EQUITY_SUPER;
        if (value.equals("Esanda")) return ESANDA;
        if (value.equals("Essential Super")) return ESSENTIAL_SUPER;
        if (value.equals("Ezy Bank")) return EZY_BANK;
        if (value.equals("FAI")) return FAI;
        if (value.equals("FASTLend")) return FAST_LEND;
        if (value.equals("Federation")) return FEDERATION;
        if (value.equals("Fire Brigades Credit Union")) return FIRE_BRIGADES_CREDIT_UNION;
        if (value.equals("Fire Service Credit Union")) return FIRE_SERVICE_CREDIT_UNION;
        if (value.equals("Firstmac")) return FIRSTMAC;
        if (value.equals("First Choice Credit Union")) return FIRST_CHOICE_CREDIT_UNION;
        if (value.equals("First National Bank of Chicago")) return FIRST_NATIONAL_BANK_OF_CHICAGO;
        if (value.equals("First Permanent Home Loans")) return FIRST_PERMANENT_HOME_LOANS;
        if (value.equals("First Provincial Building Society")) return FIRST_PROVINCIAL_BUILDING_SOCIETY;
        if (value.equals("First State Super")) return FIRST_STATE_SUPER;
        if (value.equals("First Super")) return FIRST_SUPER;
        if (value.equals("Flexirent")) return FLEXIRENT;
        if (value.equals("Ford Credit")) return FORD_CREDIT;
        if (value.equals("Fortis")) return FORTIS;
        if (value.equals("Fundcorp")) return FUNDCORP;
        if (value.equals("Future Financial")) return FUTURE_FINANCIAL;
        if (value.equals("Gateway Credit Union")) return GATEWAY_CREDIT_UNION;
        if (value.equals("Genworth")) return GENWORTH;
        if (value.equals("GE Automotive")) return GE_AUTOMOTIVE;
        if (value.equals("GE Capital Finance")) return GE_CAPITAL_FINANCE;
        if (value.equals("GE Capital Finance (Go Mastercard)")) return GE_CAPITAL_FINANCE_GO_MASTERCARD;
        if (value.equals("GE Credit Line")) return GE_CREDIT_LINE;
        if (value.equals("Ge Finance")) return GE_FINANCE;
        if (value.equals("GE Money Aust Pty Ltd")) return GE_MONEY_AUST_PTY_LTD;
        if (value.equals("GE Mortgages")) return GE_MORTGAGES;
        if (value.equals("GIO")) return GIO;
        if (value.equals("GIO Building Society")) return GIO_BUILDING_SOCIETY;
        if (value.equals("GMAC Finance")) return GMAC_FINANCE;
        if (value.equals("Grace Bros")) return GRACE_BROS;
        if (value.equals("GRE")) return GRE;
        if (value.equals("Greater Building Society")) return GREATER_BUILDING_SOCIETY;
        if (value.equals("Great Pacific Financial")) return GREAT_PACIFIC_FINANCIAL;
        if (value.equals("Guild")) return GUILD;
        if (value.equals("Hanover Consumer Finance")) return HANOVER_CONSUMER_FINANCE;
        if (value.equals("HBF")) return HBF;
        if (value.equals("Heritage")) return HERITAGE;
        if (value.equals("HESTA")) return HESTA;
        if (value.equals("Homeloans Ltd")) return HOMELOANS_LTD;
        if (value.equals("Homeside")) return HOMESIDE;
        if (value.equals("Homestart Finance")) return HOMESTART_FINANCE;
        if (value.equals("Homeswest")) return HOMESWEST;
        if (value.equals("Home Building Society")) return HOME_BUILDING_SOCIETY;
        if (value.equals("HSBC")) return HSBC;
        if (value.equals("Hume Building Society")) return HUME_BUILDING_SOCIETY;
        if (value.equals("IBJ Australia Bank")) return IBJ_AUSTRALIA_BANK;
        if (value.equals("Iden")) return IDEN;
        if (value.equals("Ignite")) return IGNITE;
        if (value.equals("Illawarra Building Society")) return ILLAWARRA_BUILDING_SOCIETY;
        if (value.equals("IMB Ltd")) return IMB_LTD;
        if (value.equals("INC Invest")) return INC_INVEST;
        if (value.equals("ING")) return ING;
        if (value.equals("ING Mercantile Mutual Bank")) return ING_MERCANTILE_MUTUAL_BANK;
        if (value.equals("Intech Credit Union")) return INTECH_CREDIT_UNION;
        if (value.equals("International Acceptance")) return INTERNATIONAL_ACCEPTANCE;
        if (value.equals("International Commercial Bank of China")) return INTERNATIONAL_COMMERCIAL_BANK_OF_CHINA;
        if (value.equals("Investec")) return INVESTEC;
        if (value.equals("InTrust")) return IN_TRUST;
        if (value.equals("IOOF Building Society")) return IOOF_BUILDING_SOCIETY;
        if (value.equals("Keystart Home Loans")) return KEYSTART_HOME_LOANS;
        if (value.equals("Kinetic")) return KINETIC;
        if (value.equals("Kwik Kash International")) return KWIK_KASH_INTERNATIONAL;
        if (value.equals("LaTrobe")) return LA_TROBE;
        if (value.equals("Legal Super")) return LEGAL_SUPER;
        if (value.equals("Liberty")) return LIBERTY;
        if (value.equals("Lion Finance")) return LION_FINANCE;
        if (value.equals("Loanave")) return LOANAVE;
        if (value.equals("Local Government")) return LOCAL_GOVERNMENT;
        if (value.equals("Lombard Finance")) return LOMBARD_FINANCE;
        if (value.equals("LUCRF")) return LUCRF;
        if (value.equals("Macarthur Credit Union")) return MACARTHUR_CREDIT_UNION;
        if (value.equals("Mackay Permanent Building Society")) return MACKAY_PERMANENT_BUILDING_SOCIETY;
        if (value.equals("Macquarie")) return MACQUARIE;
        if (value.equals("Maitland Mutual Building Society")) return MAITLAND_MUTUAL_BUILDING_SOCIETY;
        if (value.equals("Manufacture Mutual")) return MANUFACTURE_MUTUAL;
        if (value.equals("MAP")) return MAP;
        if (value.equals("Media Super")) return MEDIA_SUPER;
        if (value.equals("Mediplan Australia")) return MEDIPLAN_AUSTRALIA;
        if (value.equals("Members Equity Bank")) return MEMBERS_EQUITY_BANK;
        if (value.equals("Mercantile Mutual")) return MERCANTILE_MUTUAL;
        if (value.equals("Mercer Wealth")) return MERCER_WEALTH;
        if (value.equals("ME Bank")) return ME_BANK;
        if (value.equals("Midland Bank PLC")) return MIDLAND_BANK_PLC;
        if (value.equals("MIIP")) return MIIP;
        if (value.equals("Mine Wealth and Wellbeing")) return MINE_WEALTH_AND_WELLBEING;
        if (value.equals("MIS")) return MIS;
        if (value.equals("Mitchell Building Society")) return MITCHELL_BUILDING_SOCIETY;
        if (value.equals("MKM Capital")) return MKM_CAPITAL;
        if (value.equals("MLC")) return MLC;
        if (value.equals("MMI")) return MMI;
        if (value.equals("Morgan Guaranty Trust Bank of New York")) return MORGAN_GUARANTY_TRUST_BANK_OF_NEW_YORK;
        if (value.equals("Mortgage Ezy")) return MORTGAGE_EZY;
        if (value.equals("Mortgage House")) return MORTGAGE_HOUSE;
        if (value.equals("Mortgage Mart")) return MORTGAGE_MART;
        if (value.equals("MTAA")) return MTAA;
        if (value.equals("Mutual Community")) return MUTUAL_COMMUNITY;
        if (value.equals("M Capitol")) return M_CAPITOL;
        if (value.equals("NAB")) return NAB;
        if (value.equals("National Mortgage Corporation")) return NATIONAL_MORTGAGE_CORPORATION;
        if (value.equals("Natwest Markets Australia")) return NATWEST_MARKETS_AUSTRALIA;
        if (value.equals("NCUIS")) return NCUIS;
        if (value.equals("Newcastle Permanent Building Society")) return NEWCASTLE_PERMANENT_BUILDING_SOCIETY;
        if (value.equals("NGS")) return NGS;
        if (value.equals("Northern Building Society")) return NORTHERN_BUILDING_SOCIETY;
        if (value.equals("NRMA")) return NRMA;
        if (value.equals("NSF Super")) return NSF_SUPER;
        if (value.equals("NSW Home Loans")) return NSW_HOME_LOANS;
        if (value.equals("NSW Teachers Credit Union")) return NSW_TEACHERS_CREDIT_UNION;
        if (value.equals("NZI")) return NZI;
        if (value.equals("OneAnswer")) return ONE_ANSWER;
        if (value.equals("ORIX")) return ORIX;
        if (value.equals("Other")) return OTHER;
        if (value.equals("Overseas-Chinese Banking Corporation")) return OVERSEAS_CHINESE_BANKING_CORPORATION;
        if (value.equals("Paramount")) return PARAMOUNT;
        if (value.equals("Payday Central")) return PAYDAY_CENTRAL;
        if (value.equals("Pensioners Insurance")) return PENSIONERS_INSURANCE;
        if (value.equals("People's Choice Credit Union")) return PEOPLE_S_CHOICE_CREDIT_UNION;
        if (value.equals("Pepper")) return PEPPER;
        if (value.equals("Perpetual Limited")) return PERPETUAL_LIMITED;
        if (value.equals("Perpetual Trustee")) return PERPETUAL_TRUSTEE;
        if (value.equals("Pioneer Permanent Building Society")) return PIONEER_PERMANENT_BUILDING_SOCIETY;
        if (value.equals("PLANLend")) return PLAN_LEND;
        if (value.equals("Plum")) return PLUM;
        if (value.equals("Police and Nurses")) return POLICE_AND_NURSES;
        if (value.equals("Police Credit Union")) return POLICE_CREDIT_UNION;
        if (value.equals("Police Credit Union (NSW)")) return POLICE_CREDIT_UNION_NSW;
        if (value.equals("Powerstate Credit Union")) return POWERSTATE_CREDIT_UNION;
        if (value.equals("Primary Industry Bank of Australia")) return PRIMARY_INDUSTRY_BANK_OF_AUSTRALIA;
        if (value.equals("Prime")) return PRIME;
        if (value.equals("Prospect Credit Union")) return PROSPECT_CREDIT_UNION;
        if (value.equals("Public Trustee")) return PUBLIC_TRUSTEE;
        if (value.equals("Pulse Credit Union")) return PULSE_CREDIT_UNION;
        if (value.equals("QANTAS Credit Union")) return QANTAS_CREDIT_UNION;
        if (value.equals("QBE")) return QBE;
        if (value.equals("Qudos Bank")) return QUDOS_BANK;
        if (value.equals("Queensland Country Credit Union")) return QUEENSLAND_COUNTRY_CREDIT_UNION;
        if (value.equals("Queensland Credit Union")) return QUEENSLAND_CREDIT_UNION;
        if (value.equals("Queensland Industry Development Corp")) return QUEENSLAND_INDUSTRY_DEVELOPMENT_CORP;
        if (value.equals("Queensland Professional Credit Union")) return QUEENSLAND_PROFESSIONAL_CREDIT_UNION;
        if (value.equals("Queensland Teachers Credit Union")) return QUEENSLAND_TEACHERS_CREDIT_UNION;
        if (value.equals("RAC")) return RAC;
        if (value.equals("RACV")) return RACV;
        if (value.equals("RAC WA")) return RAC_WA;
        if (value.equals("Radio Rentals")) return RADIO_RENTALS;
        if (value.equals("Railways Credit Union")) return RAILWAYS_CREDIT_UNION;
        if (value.equals("RAMS")) return RAMS;
        if (value.equals("REA Home Loans")) return REA_HOME_LOANS;
        if (value.equals("Repcol")) return REPCOL;
        if (value.equals("Reserve Bank of Australia")) return RESERVE_BANK_OF_AUSTRALIA;
        if (value.equals("Resi")) return RESI;
        if (value.equals("RESIMAC")) return RESIMAC;
        if (value.equals("RESI Mortgage Corporation")) return RESI_MORTGAGE_CORPORATION;
        if (value.equals("Royal Life")) return ROYAL_LIFE;
        if (value.equals("Russell Investments")) return RUSSELL_INVESTMENTS;
        if (value.equals("Safrock Finance")) return SAFROCK_FINANCE;
        if (value.equals("Sanwa Australia Finance Limited")) return SANWA_AUSTRALIA_FINANCE_LIMITED;
        if (value.equals("Savings And Loans Credit Union")) return SAVINGS_AND_LOANS_CREDIT_UNION;
        if (value.equals("SGIC")) return SGIC;
        if (value.equals("SGIO")) return SGIO;
        if (value.equals("Shannons")) return SHANNONS;
        if (value.equals("SmartSave")) return SMART_SAVE;
        if (value.equals("Southern Cross Credit Union")) return SOUTHERN_CROSS_CREDIT_UNION;
        if (value.equals("Sovereign Credit")) return SOVEREIGN_CREDIT;
        if (value.equals("Standard Chartered Bank Aust")) return STANDARD_CHARTERED_BANK_AUST;
        if (value.equals("Statewide")) return STATEWIDE;
        if (value.equals("State Street Bank And Trust Company")) return STATE_STREET_BANK_AND_TRUST_COMPANY;
        if (value.equals("Stronghold")) return STRONGHOLD;
        if (value.equals("St Andrew")) return ST_ANDREW;
        if (value.equals("St George")) return ST_GEORGE;
        if (value.equals("Summerland Credit Union")) return SUMMERLAND_CREDIT_UNION;
        if (value.equals("Suncorp")) return SUNCORP;
        if (value.equals("Suncorp Metway")) return SUNCORP_METWAY;
        if (value.equals("Sunsuper")) return SUNSUPER;
        if (value.equals("Sun Alliance")) return SUN_ALLIANCE;
        if (value.equals("Swann")) return SWANN;
        if (value.equals("TasPlan")) return TAS_PLAN;
        if (value.equals("Teachers Credit Union")) return TEACHERS_CREDIT_UNION;
        if (value.equals("Teachers Mutual")) return TEACHERS_MUTUAL;
        if (value.equals("Territory Mutual Building Society")) return TERRITORY_MUTUAL_BUILDING_SOCIETY;
        if (value.equals("The Rock")) return THE_ROCK;
        if (value.equals("Tonto Home Loans")) return TONTO_HOME_LOANS;
        if (value.equals("Town And Country Bank")) return TOWN_AND_COUNTRY_BANK;
        if (value.equals("Toyota Finance Australia")) return TOYOTA_FINANCE_AUSTRALIA;
        if (value.equals("Trust Bank of Tasmania")) return TRUST_BANK_OF_TASMANIA;
        if (value.equals("TWUSUPER")) return TWUSUPER;
        if (value.equals("United Credit Union")) return UNITED_CREDIT_UNION;
        if (value.equals("United Overseas Bank")) return UNITED_OVERSEAS_BANK;
        if (value.equals("University Credit Society")) return UNIVERSITY_CREDIT_SOCIETY;
        if (value.equals("UBank")) return U_BANK;
        if (value.equals("VACC")) return VACC;
        if (value.equals("Vero")) return VERO;
        if (value.equals("Victoria Teachers Credit Union Ltd")) return VICTORIA_TEACHERS_CREDIT_UNION_LTD;
        if (value.equals("VicSuper")) return VIC_SUPER;
        if (value.equals("Virgin Super")) return VIRGIN_SUPER;
        if (value.equals("Visions")) return VISIONS;
        if (value.equals("Western QBE")) return WESTERN_QBE;
        if (value.equals("Westfarmers")) return WESTFARMERS;
        if (value.equals("Westpack Insurance Services")) return WESTPACK_INSURANCE_SERVICES;
        if (value.equals("Westpac Bank")) return WESTPAC_BANK;
        if (value.equals("Wide Bay Capricorn Building Society")) return WIDE_BAY_CAPRICORN_BUILDING_SOCIETY;
        if (value.equals("Wizard")) return WIZARD;
        if (value.equals("World Marine and General")) return WORLD_MARINE_AND_GENERAL;
        if (value.equals("Zurich")) return ZURICH;
        throw new IOException("Cannot deserialize FinancialInstitutionList");
    }
}
