package io.model;

import java.io.IOException;
import com.fasterxml.jackson.annotation.*;

public enum InsurerList {
    AAMI, AIA_AUSTRALIA, ALLIANZ_AUSTRALIA, AMP_LIMITED, API, APIA, ASTERON_LIFE_SUNCORP, ATRADIUS, AUSTRALIAN_PENSIONERS_INSURANCE, AUSTRALIAN_UNITY, AUTO_AND_GENERAL_INSURANCE, AXA_AUSTRALIA, BINGLE, BUPA_AUSTRALIA, BUZZ, CALLIDEN_INSURANCE, CGU_INSURANCE, CHU, CHUBB, CIC, CIL, COLONIAL, COMMONWEALTH_BANK, COMM_INSURE, DEFENCE_SERVICES_HOMES, ELDERS, ESANDA, FAI, FORTIS, GENWORTH_FINANCIAL, GIO, GUARDIAN_INSURANCE, GUILD, HBF, ING, INSURANCE_AUSTRALIA_GROUP, INSURE_MY_RIDE, JUST_CAR, LFI_GROUP_PTY_LTD, LIFEBROKER, MACQUARIE_LIFE, MANCHESTER_UNITY_AUSTRALIA, MEDIBANK_PRIVATE, MERCANTILE_MUTUAL, MLC, MMI, MUTUAL_COMMUNITY, NCUIS, NIB_HEALTH_FUNDS, NRMA_INSURANCE, NZI, ONE_PATH_ANZ, OTHER, QBE, QBE_INSURANCE_MEMBER_CARE, Q_REPORT_JEWELLERY_INSURANCE, RAC, RACQ_INSURANCE, RACV, RAC_WA, REAL_INSURANCE, REDWOOD_ADVISORY, SGIC, SGIO, SHANNONS, SMART_BUSINESS_INSURANCE_PTY_LTD, SUNCORP, SUN_ALLIANCE, SUPERANNUATION_WAREHOUSE, SUPER_CHEAP_AUTO_GROUP, SWANN, TAL_TOWER_AUSTRALIA, TERRI_SCHEER, TIO, TRADE_COVER, VACC, VERO, WESTERN_QBE, WESTFARMERS, WESTPAC_INSURANCE_SERVICES, WORLD_MARINE_AND_GENERAL, YOU_INSURED, ZURICH_AUSTRALIA;

    @JsonValue
    public String toValue() {
        switch (this) {
            case AAMI: return "AAMI";
            case AIA_AUSTRALIA: return "AIA Australia";
            case ALLIANZ_AUSTRALIA: return "Allianz Australia";
            case AMP_LIMITED: return "AMP Limited";
            case API: return "API";
            case APIA: return "APIA";
            case ASTERON_LIFE_SUNCORP: return "Asteron Life (Suncorp)";
            case ATRADIUS: return "Atradius";
            case AUSTRALIAN_PENSIONERS_INSURANCE: return "Australian Pensioners Insurance";
            case AUSTRALIAN_UNITY: return "Australian Unity";
            case AUTO_AND_GENERAL_INSURANCE: return "Auto and General Insurance";
            case AXA_AUSTRALIA: return "AXA Australia";
            case BINGLE: return "Bingle";
            case BUPA_AUSTRALIA: return "BUPA Australia";
            case BUZZ: return "Buzz";
            case CALLIDEN_INSURANCE: return "Calliden Insurance";
            case CGU_INSURANCE: return "CGU Insurance";
            case CHU: return "CHU";
            case CHUBB: return "Chubb";
            case CIC: return "CIC";
            case CIL: return "CIL";
            case COLONIAL: return "Colonial";
            case COMMONWEALTH_BANK: return "Commonwealth Bank";
            case COMM_INSURE: return "CommInsure";
            case DEFENCE_SERVICES_HOMES: return "Defence Services Homes";
            case ELDERS: return "Elders";
            case ESANDA: return "Esanda";
            case FAI: return "FAI";
            case FORTIS: return "Fortis";
            case GENWORTH_FINANCIAL: return "Genworth Financial";
            case GIO: return "GIO";
            case GUARDIAN_INSURANCE: return "Guardian Insurance";
            case GUILD: return "Guild";
            case HBF: return "HBF";
            case ING: return "ING";
            case INSURANCE_AUSTRALIA_GROUP: return "Insurance Australia Group";
            case INSURE_MY_RIDE: return "InsureMyRide";
            case JUST_CAR: return "Just Car";
            case LFI_GROUP_PTY_LTD: return "LFI Group Pty Ltd";
            case LIFEBROKER: return "Lifebroker";
            case MACQUARIE_LIFE: return "Macquarie Life";
            case MANCHESTER_UNITY_AUSTRALIA: return "Manchester Unity Australia";
            case MEDIBANK_PRIVATE: return "Medibank Private";
            case MERCANTILE_MUTUAL: return "Mercantile Mutual";
            case MLC: return "MLC";
            case MMI: return "MMI";
            case MUTUAL_COMMUNITY: return "Mutual Community";
            case NCUIS: return "NCUIS";
            case NIB_HEALTH_FUNDS: return "NIB Health Funds";
            case NRMA_INSURANCE: return "NRMA Insurance";
            case NZI: return "NZI";
            case ONE_PATH_ANZ: return "OnePath (ANZ)";
            case OTHER: return "Other";
            case QBE: return "QBE";
            case QBE_INSURANCE_MEMBER_CARE: return "QBE Insurance - MemberCare";
            case Q_REPORT_JEWELLERY_INSURANCE: return "Q Report Jewellery Insurance";
            case RAC: return "RAC";
            case RACQ_INSURANCE: return "RACQ Insurance";
            case RACV: return "RACV";
            case RAC_WA: return "RAC WA";
            case REAL_INSURANCE: return "Real Insurance";
            case REDWOOD_ADVISORY: return "Redwood Advisory";
            case SGIC: return "SGIC";
            case SGIO: return "SGIO";
            case SHANNONS: return "Shannons";
            case SMART_BUSINESS_INSURANCE_PTY_LTD: return "Smart Business Insurance Pty Ltd.";
            case SUNCORP: return "Suncorp";
            case SUN_ALLIANCE: return "Sun Alliance";
            case SUPERANNUATION_WAREHOUSE: return "Superannuation Warehouse";
            case SUPER_CHEAP_AUTO_GROUP: return "Super Cheap Auto Group";
            case SWANN: return "Swann";
            case TAL_TOWER_AUSTRALIA: return "TAL (Tower Australia)";
            case TERRI_SCHEER: return "Terri Scheer";
            case TIO: return "TIO";
            case TRADE_COVER: return "TradeCover";
            case VACC: return "VACC";
            case VERO: return "Vero";
            case WESTERN_QBE: return "Western QBE";
            case WESTFARMERS: return "Westfarmers";
            case WESTPAC_INSURANCE_SERVICES: return "Westpac Insurance Services";
            case WORLD_MARINE_AND_GENERAL: return "World Marine and General";
            case YOU_INSURED: return "You.insured";
            case ZURICH_AUSTRALIA: return "Zurich Australia";
        }
        return null;
    }

    @JsonCreator
    public static InsurerList forValue(String value) throws IOException {
        if (value.equals("AAMI")) return AAMI;
        if (value.equals("AIA Australia")) return AIA_AUSTRALIA;
        if (value.equals("Allianz Australia")) return ALLIANZ_AUSTRALIA;
        if (value.equals("AMP Limited")) return AMP_LIMITED;
        if (value.equals("API")) return API;
        if (value.equals("APIA")) return APIA;
        if (value.equals("Asteron Life (Suncorp)")) return ASTERON_LIFE_SUNCORP;
        if (value.equals("Atradius")) return ATRADIUS;
        if (value.equals("Australian Pensioners Insurance")) return AUSTRALIAN_PENSIONERS_INSURANCE;
        if (value.equals("Australian Unity")) return AUSTRALIAN_UNITY;
        if (value.equals("Auto and General Insurance")) return AUTO_AND_GENERAL_INSURANCE;
        if (value.equals("AXA Australia")) return AXA_AUSTRALIA;
        if (value.equals("Bingle")) return BINGLE;
        if (value.equals("BUPA Australia")) return BUPA_AUSTRALIA;
        if (value.equals("Buzz")) return BUZZ;
        if (value.equals("Calliden Insurance")) return CALLIDEN_INSURANCE;
        if (value.equals("CGU Insurance")) return CGU_INSURANCE;
        if (value.equals("CHU")) return CHU;
        if (value.equals("Chubb")) return CHUBB;
        if (value.equals("CIC")) return CIC;
        if (value.equals("CIL")) return CIL;
        if (value.equals("Colonial")) return COLONIAL;
        if (value.equals("Commonwealth Bank")) return COMMONWEALTH_BANK;
        if (value.equals("CommInsure")) return COMM_INSURE;
        if (value.equals("Defence Services Homes")) return DEFENCE_SERVICES_HOMES;
        if (value.equals("Elders")) return ELDERS;
        if (value.equals("Esanda")) return ESANDA;
        if (value.equals("FAI")) return FAI;
        if (value.equals("Fortis")) return FORTIS;
        if (value.equals("Genworth Financial")) return GENWORTH_FINANCIAL;
        if (value.equals("GIO")) return GIO;
        if (value.equals("Guardian Insurance")) return GUARDIAN_INSURANCE;
        if (value.equals("Guild")) return GUILD;
        if (value.equals("HBF")) return HBF;
        if (value.equals("ING")) return ING;
        if (value.equals("Insurance Australia Group")) return INSURANCE_AUSTRALIA_GROUP;
        if (value.equals("InsureMyRide")) return INSURE_MY_RIDE;
        if (value.equals("Just Car")) return JUST_CAR;
        if (value.equals("LFI Group Pty Ltd")) return LFI_GROUP_PTY_LTD;
        if (value.equals("Lifebroker")) return LIFEBROKER;
        if (value.equals("Macquarie Life")) return MACQUARIE_LIFE;
        if (value.equals("Manchester Unity Australia")) return MANCHESTER_UNITY_AUSTRALIA;
        if (value.equals("Medibank Private")) return MEDIBANK_PRIVATE;
        if (value.equals("Mercantile Mutual")) return MERCANTILE_MUTUAL;
        if (value.equals("MLC")) return MLC;
        if (value.equals("MMI")) return MMI;
        if (value.equals("Mutual Community")) return MUTUAL_COMMUNITY;
        if (value.equals("NCUIS")) return NCUIS;
        if (value.equals("NIB Health Funds")) return NIB_HEALTH_FUNDS;
        if (value.equals("NRMA Insurance")) return NRMA_INSURANCE;
        if (value.equals("NZI")) return NZI;
        if (value.equals("OnePath (ANZ)")) return ONE_PATH_ANZ;
        if (value.equals("Other")) return OTHER;
        if (value.equals("QBE")) return QBE;
        if (value.equals("QBE Insurance - MemberCare")) return QBE_INSURANCE_MEMBER_CARE;
        if (value.equals("Q Report Jewellery Insurance")) return Q_REPORT_JEWELLERY_INSURANCE;
        if (value.equals("RAC")) return RAC;
        if (value.equals("RACQ Insurance")) return RACQ_INSURANCE;
        if (value.equals("RACV")) return RACV;
        if (value.equals("RAC WA")) return RAC_WA;
        if (value.equals("Real Insurance")) return REAL_INSURANCE;
        if (value.equals("Redwood Advisory")) return REDWOOD_ADVISORY;
        if (value.equals("SGIC")) return SGIC;
        if (value.equals("SGIO")) return SGIO;
        if (value.equals("Shannons")) return SHANNONS;
        if (value.equals("Smart Business Insurance Pty Ltd.")) return SMART_BUSINESS_INSURANCE_PTY_LTD;
        if (value.equals("Suncorp")) return SUNCORP;
        if (value.equals("Sun Alliance")) return SUN_ALLIANCE;
        if (value.equals("Superannuation Warehouse")) return SUPERANNUATION_WAREHOUSE;
        if (value.equals("Super Cheap Auto Group")) return SUPER_CHEAP_AUTO_GROUP;
        if (value.equals("Swann")) return SWANN;
        if (value.equals("TAL (Tower Australia)")) return TAL_TOWER_AUSTRALIA;
        if (value.equals("Terri Scheer")) return TERRI_SCHEER;
        if (value.equals("TIO")) return TIO;
        if (value.equals("TradeCover")) return TRADE_COVER;
        if (value.equals("VACC")) return VACC;
        if (value.equals("Vero")) return VERO;
        if (value.equals("Western QBE")) return WESTERN_QBE;
        if (value.equals("Westfarmers")) return WESTFARMERS;
        if (value.equals("Westpac Insurance Services")) return WESTPAC_INSURANCE_SERVICES;
        if (value.equals("World Marine and General")) return WORLD_MARINE_AND_GENERAL;
        if (value.equals("You.insured")) return YOU_INSURED;
        if (value.equals("Zurich Australia")) return ZURICH_AUSTRALIA;
        throw new IOException("Cannot deserialize InsurerList");
    }
}
